// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/claims": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Claim food from a listing for a specific food request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Claims"
                ],
                "summary": "Create a food claim",
                "operationId": "create-claim",
                "parameters": [
                    {
                        "description": "Claim information",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateClaimRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.HandlerResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "responseData": {
                                            "$ref": "#/definitions/domain.FoodClaim"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.HandlerResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.HandlerResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/dto.HandlerResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.HandlerResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/dto.HandlerResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.HandlerResponse"
                        }
                    }
                }
            }
        },
        "/claims/{claim_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Return a claim belonging to the authenticated user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Claims"
                ],
                "summary": "Get claim by ID",
                "operationId": "get-claim",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Claim ID",
                        "name": "claim_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.HandlerResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "responseData": {
                                            "$ref": "#/definitions/domain.FoodClaim"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.HandlerResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.HandlerResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/dto.HandlerResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.HandlerResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.HandlerResponse"
                        }
                    }
                }
            }
        },
        "/claims/{claim_id}/cancel": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Cancel a food claim belonging to the authenticated user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Claims"
                ],
                "summary": "Cancel a claim",
                "operationId": "cancel-claim",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Claim ID",
                        "name": "claim_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.HandlerResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "responseData": {
                                            "$ref": "#/definitions/domain.FoodClaim"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.HandlerResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.HandlerResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/dto.HandlerResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.HandlerResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/dto.HandlerResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.HandlerResponse"
                        }
                    }
                }
            }
        },
        "/claims/{claim_id}/verify-pickup": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Verify the claim pickup code and mark the claim as completed",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Claims"
                ],
                "summary": "Verify a pickup code",
                "operationId": "verify-pickup-code",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Claim ID",
                        "name": "claim_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Pickup verification information",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.VerifyPickupRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.HandlerResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "responseData": {
                                            "$ref": "#/definitions/domain.FoodClaim"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.HandlerResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.HandlerResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/dto.HandlerResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.HandlerResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/dto.HandlerResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.HandlerResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.ClaimStatus": {
            "type": "string",
            "enum": [
                "waiting_for_pickup",
                "picked_up",
                "cancelled"
            ],
            "x-enum-varnames": [
                "StatusWaitingForPickup",
                "StatusPickedUp",
                "StatusCancelled"
            ]
        },
        "domain.FoodClaim": {
            "type": "object",
            "properties": {
                "claim_code": {
                    "type": "string"
                },
                "claim_id": {
                    "type": "string"
                },
                "claimed_at": {
                    "type": "string"
                },
                "claimed_quantity": {
                    "type": "integer"
                },
                "code_expires_at": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "food_listing_id": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/domain.ClaimStatus"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dto.CreateClaimRequest": {
            "type": "object",
            "properties": {
                "claimed_quantity": {
                    "type": "integer"
                },
                "food_listing_id": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                }
            }
        },
        "dto.HandlerResponse": {
            "type": "object",
            "properties": {
                "responseCode": {
                    "type": "string"
                },
                "responseData": {},
                "responseMessage": {
                    "type": "string"
                }
            }
        },
        "dto.VerifyPickupRequest": {
            "type": "object",
            "properties": {
                "claim_code": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Enter the token using: Bearer {token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8084",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "Zero Hunger Claim Service API",
	Description:      "Food claim creation, cancellation, and pickup verification API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
