// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/food-listings": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Return all currently active food listings",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Food Listings"
                ],
                "summary": "Get active food listings",
                "operationId": "get-active-food-listings",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.HandlerResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "responseData": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/domain.FoodListing"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.HandlerResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.HandlerResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.HandlerResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.HandlerResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new food listing for the authenticated donor",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Food Listings"
                ],
                "summary": "Create a food listing",
                "operationId": "create-food-listing",
                "parameters": [
                    {
                        "description": "Food listing information",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateFoodListingRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.HandlerResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "responseData": {
                                            "$ref": "#/definitions/domain.FoodListing"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.HandlerResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.HandlerResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/dto.HandlerResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.HandlerResponse"
                        }
                    }
                }
            }
        },
        "/food-listings/nearby": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Find active food listings near the location of a food request",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Food Listings"
                ],
                "summary": "Find nearby food listings",
                "operationId": "get-nearby-food-listings",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Food request ID",
                        "name": "request_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.HandlerResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "responseData": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/domain.FoodListing"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.HandlerResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.HandlerResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.HandlerResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.HandlerResponse"
                        }
                    }
                }
            }
        },
        "/food-listings/{food_listing_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Return the details of a specific food listing",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Food Listings"
                ],
                "summary": "Get food listing by ID",
                "operationId": "get-food-listing-by-id",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Food listing ID",
                        "name": "food_listing_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.HandlerResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "responseData": {
                                            "$ref": "#/definitions/domain.FoodListing"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.HandlerResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.HandlerResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.HandlerResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.HandlerResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.FoodCategory": {
            "type": "string",
            "enum": [
                "cooked_food",
                "raw_food",
                "bakery"
            ],
            "x-enum-varnames": [
                "FoodCooked",
                "FoodRaw",
                "FoodBakery"
            ]
        },
        "domain.FoodListing": {
            "type": "object",
            "properties": {
                "available_from": {
                    "type": "string"
                },
                "available_until": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "food_listing_id": {
                    "type": "string"
                },
                "food_type": {
                    "$ref": "#/definitions/domain.FoodCategory"
                },
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "quantity": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/domain.ListingStatus"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "domain.ListingStatus": {
            "type": "string",
            "enum": [
                "available",
                "claimed",
                "expired"
            ],
            "x-enum-varnames": [
                "StatusAvailable",
                "StatusClaimed",
                "StatusExpired"
            ]
        },
        "dto.CreateFoodListingRequest": {
            "type": "object",
            "required": [
                "available_from",
                "available_until",
                "food_type",
                "latitude",
                "longitude",
                "title"
            ],
            "properties": {
                "available_from": {
                    "type": "string"
                },
                "available_until": {
                    "type": "string"
                },
                "description": {
                    "type": "string",
                    "maxLength": 2000
                },
                "food_type": {
                    "type": "string",
                    "enum": [
                        "cooked_food",
                        "raw_food",
                        "bakery"
                    ]
                },
                "latitude": {
                    "type": "number",
                    "maximum": 90,
                    "minimum": -90
                },
                "longitude": {
                    "type": "number",
                    "maximum": 180,
                    "minimum": -180
                },
                "quantity": {
                    "type": "integer",
                    "minimum": 0
                },
                "title": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 3
                }
            }
        },
        "dto.HandlerResponse": {
            "type": "object",
            "properties": {
                "responseCode": {
                    "type": "string"
                },
                "responseData": {},
                "responseMessage": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Enter the token using: Bearer {token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8082",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "Zero Hunger Food Service API",
	Description:      "Food listing management and nearby food search API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
